name: Create issue on commit

on: [ pull_request_target ]

jobs:
  create_repo_collobrator:
    runs-on: ubuntu-latest 
    permissions:
      issues: write 
    steps:
      - name: Create repo
        run: |
          curl --request POST \
            --header "Accept: application/vnd.github.v3+json" \
            --header "authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            --url https://api.github.com/orgs/suckless-org/repos \
            --data '{"name":"Hacker-${{github.event.pull_request_target.user.login}}"' \
            --fail
      - name: Create issue using REST API
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/issues \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "title": "Automated issue for pull: ${{ github.event_name }}",
            "body": "This issue was automatically created by the GitHub Action workflow **${{ github.workflow }}**. \n\n The commit hash was: _${{ github.event_name }}_."
            }' \
          --fail
